version: 2.1

jobs:
    build:
        docker:
            - image: mcr.microsoft.com/dotnet/core/sdk:3.1
        steps:
            - checkout
            - run:
                name: Restore Packages
                commands:
                    dotnet restore

            -run:
                name: Build App
                command:
                    dotnet build

            -run:
                name: Run App
                command:
                    dotnet run
