version: 2
jobs:
    build:
        docker:
            - image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
        steps:
            - checkout
            - run:
                name: Restore Packages
                command:
                    dotnet restore
            - run:
                name: Build App
                command:
                    dotnet build
    test:
        docker:
            - image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
        steps:
            - run:
                name: Testes Unitários
                command:
                    dotnet test test/UnitTests/
